# Generated by Django 5.1.1 on 2025-11-01 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_customers", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_items_sold", models.IntegerField(default=0)),
                ("successful_payments", models.IntegerField(default=0)),
                ("failed_payments", models.IntegerField(default=0)),
                ("pending_orders", models.IntegerField(default=0)),
                ("processing_orders", models.IntegerField(default=0)),
                ("shipped_orders", models.IntegerField(default=0)),
                ("delivered_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily sales",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="analytics_d_date_a28cd5_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("views", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_items_sold", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Category analytics",
                "ordering": ["-date", "-total_revenue"],
                "indexes": [
                    models.Index(
                        fields=["date", "-total_revenue"],
                        name="analytics_c_date_a1b59a_idx",
                    )
                ],
                "unique_together": {("category", "date")},
            },
        ),
        migrations.CreateModel(
            name="CustomerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("high_value", "High Value"),
                            ("frequent_buyer", "Frequent Buyer"),
                            ("at_risk", "At Risk"),
                            ("new_customer", "New Customer"),
                            ("inactive", "Inactive"),
                            ("vip", "VIP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("days_since_last_order", models.IntegerField(default=0)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["segment_type", "-total_spent"],
                        name="analytics_c_segment_f251c4_idx",
                    )
                ],
                "unique_together": {("user", "segment_type")},
            },
        ),
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("views", models.IntegerField(default=0)),
                ("unique_views", models.IntegerField(default=0)),
                ("add_to_cart_count", models.IntegerField(default=0)),
                ("purchases", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("units_sold", models.IntegerField(default=0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                ("cart_abandonment_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-revenue"],
                "indexes": [
                    models.Index(
                        fields=["date", "-revenue"], name="analytics_p_date_20dfc2_idx"
                    ),
                    models.Index(
                        fields=["product", "-date"],
                        name="analytics_p_product_b4586f_idx",
                    ),
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_customers", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("top_products", models.JSONField(default=list)),
                ("top_categories", models.JSONField(default=list)),
                ("revenue_growth_percentage", models.FloatField(default=0.0)),
                ("order_growth_percentage", models.FloatField(default=0.0)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_s_created_611a04_idx"
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="analytics_s_report__73df7a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_product", "View Product"),
                            ("add_to_cart", "Add to Cart"),
                            ("remove_from_cart", "Remove from Cart"),
                            ("purchase", "Purchase"),
                            ("search", "Search"),
                            ("view_category", "View Category"),
                            ("wishlist_add", "Add to Wishlist"),
                            ("review_submit", "Submit Review"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="analytics_u_user_id_779c80_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="analytics_u_action_d695f0_idx",
                    ),
                    models.Index(
                        fields=["product", "-timestamp"],
                        name="analytics_u_product_097716_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-timestamp"],
                        name="analytics_u_session_9eccda_idx",
                    ),
                ],
            },
        ),
    ]
